name: food_delivery_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  http: ^1.2.2
  encrypt: ^5.0.0
  flutter_secure_storage: ^4.2.1
  google_maps_flutter: ^2.0.6
  permission_handler: ^10.2.0
  uuid: ^3.0.4
  geocoding: ^2.0.0
  geolocator: ^9.0.2
  url_launcher: ^6.3.0
  lottie: ^1.2.0
  flutter_webrtc: ^0.9.48
  web_socket_channel: ^3.0.1
  image_picker: ^1.1.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

flutter:

  
  uses-material-design: true


  assets:
    - assets/burger.png
    - assets/background.png
    - assets/pizza.png
    - assets/4.png
    - assets/Pizza_spinning.gif
    - assets/load.gif
   

  